<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_HargaProduk</name>
   <tag></tag>
   <elementGuidId>0cbd5391-d91f-414d-8a2c-62a8aa3585ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='harga_produk']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#harga_produk</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>409aed11-25d3-495b-bef9-0d7112af0dc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>type</value>
      <webElementGuid>967e71aa-8022-4882-b32f-063df6f5317e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c74fff07-b920-4a34-a704-82b5a45bb59a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>harga_produk</value>
      <webElementGuid>bbe9fbf8-c503-4dda-84e4-a53f4b5a73f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Rp 0,00</value>
      <webElementGuid>09ec88ab-9103-47c4-a28f-5a9699dbe980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;harga_produk&quot;)</value>
      <webElementGuid>5bc77aab-1b62-46ef-a21a-f4caa30d773d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='harga_produk']</value>
      <webElementGuid>b69fe14d-2a51-47eb-87f2-068daeed52c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[2]/input</value>
      <webElementGuid>84209c8e-f7ce-4638-9f1c-3a1894699d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>1dffca78-7acd-4e5c-914a-f13ece8e301c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'type' and @id = 'harga_produk' and @placeholder = 'Rp 0,00']</value>
      <webElementGuid>487fb4ec-0807-4b7d-8f6b-0bea322f945c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
